apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  containers:
    - name: liveness
      image: busybox:1.32
      command:
        - /bin/sh
        - -c
        - |
          touch /tmp/healthy
          sleep 5
          rm -f /tmp/healthy
          sleep 20
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 1
        periodSeconds: 1
        failureThreshold: 1
