apiVersion: v1
kind: Pod
metadata: 
  name: pod-multi
spec:
  volumes:
    - name: myvol
      emptyDir:
        sizeLimit: 10Mi
  initContainers:
    - name: config-creator
      image: busybox:1.32.0
      command:
        - /bin/sh
        - -c
        - |
          echo "$(date) here is your config" > /mnt/vol/init1.txt
          sleep 5
      volumeMounts:
        - name: myvol
          mountPath: /mnt/vol
    - name: git-cloner
      image: busybox:1.32.0
      command:  
        - /bin/sh
        - -c
        - echo "$(date) here is your git repository" > /mnt/vol/init2.txt
      volumeMounts:
        - name: myvol
          mountPath: /mnt/vol
  containers:
    - name: nginx
      image: nginx:1.17
      volumeMounts:
        - name: myvol
          mountPath: /mnt/vol
    - name: debugger
      image: alpine:3.11.3
      command:
        - sleep
        - infinity
      volumeMounts:
        - name: myvol
          mountPath: /mnt/vol


