# Variables
BOX="ubuntu/focal64"
IP_NW = "192.168.100."

MASTER_IP_START = 10
MASTER_COUNT = 1
MASTER_NAME = "raw-kubemaster"
MASTER_MEMORY_MB = "2048"
MASTER_CPU_COUNT = "2"

WORKER_IP_START = 50
WORKER_COUNT = 2
WORKER_NAME = "raw-kubeworker"
WORKER_MEMORY_MB = "2048"
WORKER_CPU_COUNT = "2"

# Environment variables
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
    config.vm.box = BOX
    config.ssh.forward_agent = true

    # Provision Master Node
    (1..MASTER_COUNT).each do |i|
        config.vm.define "#{MASTER_NAME}-#{i}" do |master|
            master.vm.network :private_network,
                ip: IP_NW + "#{MASTER_IP_START + i}",
                auto_config: true
            master.vm.hostname = "#{MASTER_NAME}-#{i}"
            master.vm.provider "virtualbox" do |virtualbox|
                virtualbox.name = "#{MASTER_NAME}-#{i}"
                virtualbox.memory = MASTER_MEMORY_MB
                virtualbox.cpus = MASTER_CPU_COUNT
                virtualbox.gui = false
            end
        end
    end

    # Provision Worker Nodes
    (1..WORKER_COUNT).each do |i|
        config.vm.define "#{WORKER_NAME}-#{i}" do |worker|
            worker.vm.network :private_network,
                ip: IP_NW + "#{WORKER_IP_START + i}",
                auto_config: true
            worker.vm.hostname = "#{WORKER_NAME}-#{i}"
            worker.vm.provider :virtualbox do |virtualbox|
                virtualbox.name = "#{WORKER_NAME}-#{i}"
                virtualbox.memory = WORKER_MEMORY_MB
                virtualbox.cpus = WORKER_CPU_COUNT
                virtualbox.gui = false
            end
        end
    end
end