# Variables
BOX="omidb11m/ubuntu-k8s"
BOX_VERSION="0.1.1"
USER="anisa"
PASSWORD="qazwsx"
SSH_WITH_PASS="true"
PUBLIC_KEY=""
PRIVATE_INTERFACE_NAME="enp0s8"
IP_NW = "192.168.200."
PREFIX = "ha"

MASTER_IP_START = 10
MASTER_COUNT = 3
MASTER_NAME = "#{PREFIX}-kubemaster"
MASTER_MEMORY_MB = "2048"
MASTER_CPU_COUNT = "2"

WORKER_IP_START = 50
WORKER_COUNT = 1
WORKER_NAME = "#{PREFIX}-kubeworker"
WORKER_MEMORY_MB = "2048"
WORKER_CPU_COUNT = "2"

LB_IP_START= 80
LB_COUNT = 1
LB_NAME = "#{PREFIX}-kubeapilb"
LB_MEMORY_MB = "1024"
LB_CPU_COUNT = "1"

# Environment variables
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
    config.vm.box = BOX
    config.vm.box_version = BOX_VERSION
    config.ssh.forward_agent = true
    config.hostmanager.enabled = true
    config.hostmanager.manage_guest = true

    config.vm.provision "setup-hosts", :type => "shell", :path => "../../scripts/setup-hosts.sh" do |s|
        s.env = {
            PRIVATE_INTERFACE_NAME: PRIVATE_INTERFACE_NAME,
            IP_NW: IP_NW,
            MASTER_IP_START: MASTER_IP_START,
            MASTER_COUNT: MASTER_COUNT,
            MASTER_NAME: MASTER_NAME,
            WORKER_IP_START: WORKER_IP_START,
            WORKER_COUNT: WORKER_COUNT,
            WORKER_NAME: WORKER_NAME,
            LB_IP_START: LB_IP_START,
            LB_COUNT: LB_COUNT,
            LB_NAME: LB_NAME
        }
    end
    config.vm.provision "setup-password", :type => "shell", :path => "../../scripts/setup-password.sh" do |s|
        s.env = {
            USER: USER,
            PASSWORD: PASSWORD
        }
    end
    config.vm.provision "setup-ssh", :type => "shell", :path => "../../scripts/setup-ssh.sh" do |s|
        s.env = {
            USER: USER,
            SSH_WITH_PASS: SSH_WITH_PASS,
            PUBLIC_KEY: PUBLIC_KEY
        }
    end

    # Provision Master Node
    (1..MASTER_COUNT).each do |i|
        config.vm.define "#{MASTER_NAME}-#{i}" do |master|
            master.vm.network :private_network,
                ip: IP_NW + "#{MASTER_IP_START + i}",
                auto_config: true
            master.vm.hostname = "#{MASTER_NAME}-#{i}"
            master.vm.provider "virtualbox" do |virtualbox|
                virtualbox.name = "#{MASTER_NAME}-#{i}"
                virtualbox.memory = MASTER_MEMORY_MB
                virtualbox.cpus = MASTER_CPU_COUNT
                virtualbox.gui = false
            end
        end
    end

    # Provision Worker Nodes
    (1..WORKER_COUNT).each do |i|
        config.vm.define "#{WORKER_NAME}-#{i}" do |worker|
            worker.vm.network :private_network,
                ip: IP_NW + "#{WORKER_IP_START + i}",
                auto_config: true
            worker.vm.hostname = "#{WORKER_NAME}-#{i}"
            worker.vm.provider :virtualbox do |virtualbox|
                virtualbox.name = "#{WORKER_NAME}-#{i}"
                virtualbox.memory = WORKER_MEMORY_MB
                virtualbox.cpus = WORKER_CPU_COUNT
                virtualbox.gui = false
            end
        end
    end

    # Provision LB Nodes
    (1..LB_COUNT).each do |i|
        config.vm.define "#{LB_NAME}-#{i}" do |lb|
            lb.vm.network :private_network,
                ip: IP_NW + "#{LB_IP_START + i}",
                auto_config: true
            lb.vm.hostname = "#{LB_NAME}-#{i}"
            lb.vm.provider :virtualbox do |virtualbox|
                virtualbox.name = "#{LB_NAME}-#{i}"
                virtualbox.memory = LB_MEMORY_MB
                virtualbox.cpus = LB_CPU_COUNT
                virtualbox.gui = false
            end
            lb.vm.provision "setup-lb", :type => "shell", :path => "../../scripts/setup-lb.sh" do |s|
                s.env = {
                    MASTER_COUNT: MASTER_COUNT,
                    MASTER_NAME: MASTER_NAME
                }
            end
        end
    end
end