apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.200.11
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
clusterName: ha-kubernetes
kubernetesVersion: v1.18.12
controlPlaneEndpoint: ha-kubeapilb-1:6443
networking:
  podSubnet: 10.244.0.0/16